name: "✨ Feature request"
description: "Suggest a new idea or feature"
title: "[Feat] "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "What do you want to add? Describe the feature in 1–2 sentences."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this feature valuable?"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Detailed description"
      description: "Provide more context, user stories, or examples of how the feature should work"
      placeholder: "As a user, I want to ... so that ..."
    validations:
      required: false

  - type: textarea
    id: media
    attributes:
      label: "Screenshots or videos"
      description: "If possible, attach screenshots or a video showing this feature in other apps, or include your own design mockups"
      placeholder: "Drag & drop files here, or paste image/video links"
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Did you consider other solutions?"
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: "Proposed technical implementation"
      description: "If you have ideas about how this could be implemented technically, describe them"
      placeholder: "e.g., Add new API endpoint / Extend existing module / UI changes"
    validations:
      required: false
